runtime: php72

handlers:
- url: /
  script: auto

- url: /index\.html
  script: auto
#
# - url: /stylesheets
#   static_dir: stylesheets

# - url: /(.*\.(gif|png|jpg))$
#   static_files: static/\1
#   upload: static/.*\.(gif|png|jpg)$
#
# - url: /admin/.*
#   script: admin.php
#   login: admin

# Fonts and images

- url: /(.+\.(eot|otf|tt[cf]|woff2?|cur|gif|ico|jpe?g|png|svgz?|webp))
  static_files: \1
  upload: (.+\.(eot|otf|tt[cf]|woff2?|cur|gif|ico|jpe?g|png|svgz?|webp))
  http_headers:
    # Allow cross-origin access to web fonts and images
    # You can also replace "*" with a specific host, e.g. https://example.org
    Access-Control-Allow-Origin: "*"

# CSS, Javascript, text, json and other file types

- url: /(.+\.(css|js|xml|txt|json))
  static_files: \1
  upload: (.+\.(css|js|xml|txt|json))
  expiration: "10m"
